### ISSUE TITLE
GetTransaction - Response Code 200 bug

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Payout-API#1]
When the TRAN_Transaction.DestinationLocationID = NULL, GetTransaction always throw response code = 200. For example, Transaction = PMT0000145

However, if TRAN_Transaction.DestinationLocationID <> NULL (e.g. PMT120583) then it has not issue - response code =

**Comment by pmt-it** [comment]
Its not an issue - data quality issue

**Comment by jctopo** [comment]
We need to provide Agent ID as well in order to get Transaction.
