### ISSUE TITLE
GetTransaction()

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Payout-API#3]
AgentID (8) does not belong to MasterAgentID (4).

Need put a business rule check to see if AgentID belongs to MasterAgentID to check the validity of the credential. Also see the note noted on the screen shot - could be related if the check is in place.

![image](https://cloud.githubusercontent.com/assets/6502098/2623311/72a0e290-bce6-11e3-9487-d69818cb9f02.png)

**Comment by jctopo** [comment]
Fixed
