### ISSUE TITLE
Payout Agent Commission Calc

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Payout-API#4]
I have payout a transaction - see the SQL statement below, there are 2 records in the resultset.

select \* from Agent_AccountStatementMovs where MasterAgentID = 6

When an agent made a payment, PMT owes the agent the payout amount and commission. You have done correctly by putting 100 in the CREDIT column for the payout amount. However, you have incorrectly put down 9.60 in the DEBIT column - 9.60 should also be in the CREDIT column ( this is the money we owe the PA)

ALSO WHAT IS THE AGENT BALANCE? WHAT IS THE MEANING OF NEGATIVE NUMBER?

![image](https://cloud.githubusercontent.com/assets/6502098/2623386/0155bf5c-bceb-11e3-9076-2a8861dde7cf.png)

**Comment by jctopo** [comment]
Fixed.

Dismiss Agent Balance, we should't use this field, since the balance belongs to Master Agent.
